import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import './globals.css'
import Header from './components/layout/Header/Header'
import Footer from './components/layout/Footer/Footer'

const poppins = Poppins({
  weight: ['400', '500', '600', '700'],
  variable: '--font-poppins-sans',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} relative`}>
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  )
}
